// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twxktreqgjbochqgvhbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3eGt0cmVxZ2pib2NocWd2aGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyNTIxODksImV4cCI6MjA1MzgyODE4OX0.RHwVe5362X1GNpf3AEQxhU4eXhhtSnkwcDLxiPhAVrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);